apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: tiez1pncu-python 
  janus-idp.io/tekton: tiez1pncu-python
  backstage.io/kubernetes-id: tiez1pncu-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: tiez1pncu-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml