apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: tiez1pncu-python
  janus-idp.io/tekton: tiez1pncu-python
  backstage.io/kubernetes-id: tiez1pncu-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: tiez1pncu-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
